
ABV = {
    ' rd ' : 'road' ,
    ' rd. ' : 'road',

    ' st ' : 'street',
    ' st. ' : 'street',

    ' ave ' : 'avenue',
    
}

AS = {
    'Adams Street' :0,
    'Albert Avenue':0,
    'Almont Street':0,
    'Amelia Avenue':0,
    'Anderson Street':0,
    'Andrew Street':0,
    'Argyle Street':0,
    'Atkinson Circle':0,
    'Atlantic Street':0,
    'Banks Street':0,
    'Bartlett Pkwy':0,
    'Bartlett Road':0,
    'Bates Avenue':0,
    'Bay View Avenue':0,
    'Bayou Street':0,
    'Beach Road':0,
    'Beacon Street':0,
    'Beal Street':0,
    'Belcher Street':0,
    'Belle Isle Terrace':0,
    'Bellevue Avenue':0,
    'Bellevue Terrace':0,
    'Billows Street':0,
    'Birch Road':0,
    'Bowdoin Street':0,
    'Brewster Avenue':0,
    'Brookfield Road':0,
    'Buchanan Street':0,
    'Buckthorn Terrace':0,
    'Burrill Terrace':0,
    'Central Street':0,
    'Centre Street':0,
    'Chamberlain Avenue':0,
    'Charles Street':0,
    'Chester Avenue':0,
    'Circuit Road':0,
    'Cliff Avenue':0,
    'Cora Street':0,
    'Coral Avenue':0,
    'Corinha Beach Road':0,
    'Cottage Avenue':0,
    'Cottage Park Road':0,
    'Court Road':0,
    'Crescent Street':0,
    'Crest Avenue':0,
    'Cross Street':0,
    'Crystal Cove Avenue':0,
    'Cutler Street':0,
    'Deane Avenue':0,
    'Deepwater Street' :0,
    'Dix Street' :0,
    'Dolphin Avenue' :0,
    'Douglas Street':0,
    'Edgar Terrace':0,
    'Edgehill Road':0,
    'Edward Street':0,
    'Egleton Park':0,
    'Eleanor Court':0,
    'Elliot Street':0,
    'Elmer Avenue':0,
    'Elmwood Avenue':0,
    'Elmwood Court':0,
    'Emerson Road':0,
    'Enfield Road':0,
    'Fairview Street':0,
    'Faunbar Avenue':0,
    'Floyd Street':0,
    'Foam Street':0,
    'Forrest Street':0,
    'Frances Street':0,
    'Franklin Street':0,
    'Fremont Street':0,
    'George Street':0,
    'Girdlestone Road':0,
    'Golden Drive':0,
    'Governors Drive':0,
    'Grand View Avenue':0,
    'Green Hill Path':0,
    'Grovers Avenue':0,
    'Hadasa Way':0,
    'Hagman Road':0,
    'Hale Avenue':0,
    'Harbor View Avenue':0,
    'Harvard Street':0,
    'Hawthorn Avenue':0,
    'Hermon Street':0,
    'Highland Avenue':0,
    'Hillside Avenue':0,
    'Hutchinson Street':0,
    'Ingleside Avenue':0,
    'Irwin Street':0,
    'James Avenue':0,
    'Jefferson Street':0,
    'Jerald Street':0,
    'Johnson Avenue':0,
    'Johnson Terrace':0,
    'Kay Street':0,
    'Kennedy Drive':0,
    'Kennedy Road':0,
    'Lewis Avenue':0,
    'Lewis Terrace':0,
    'Lincoln Street':0,
    'Lincoln Terrace':0,
    'Linden Street':0,
    'Locust Street':0,
    'Locust Way':0,
    'Lorean Terrace':0,
    'Loring Road':0,
    'Lowell Road':0,
    'Madison Avenue':0,
    'Main Street':0,
    'Maple Road':0,
    'Marshall Street':0,
    'Maryland Avenue':0,
    'Medcalf Square':0,
    'Mermaid Avenue':0,
    'Michaels Mall':0,
    'Moore Street':0,
    'Morton Street':0,
    'Mugford Street':0,
    'Myrtle Avenue':0,
    'Nahant Avenue':0,
    'Neptune Avenue':0,
    'Nevada Street':0,
    'North Avenue':0,
    'Ocean Avenue':0,
    'Oceanview Street':0,
    'Oceanview Way':0,
    'Orlando Avenue':0,
    'Otis Street':0,
    'Overlook Drive':0,
    'Paine Street':0,
    'Palmyra Street':0,
    'Park Avenue':0,
    'Pauline Street':0,
    'Payson Street':0,
    'Pearl Avenue':0,
    'Pebble Avenue':0,
    'Perkins Street':0,
    'Pico Avenue':0,
    'Pleasant Court':0,
    'Pleasant Park Road':0,
    'Pleasant Street':0,
    'Plummer Avenue':0,
    'Pond Street':0,
    'Pratt Street':0,
    'Prescott Street':0,
    'Prospect Avenue':0,
    'Putnam Place':0,
    'Putnam Street':0,
    'Quincy Avenue':0,
    'Quincy Path':0,
    'Read Street':0,
    'Revere Street':0,
    'Rice Wharf':0,
    'River Road':0,
    'Russell Street':0,
    'Sagamore Avenue':0,
    'Sargent Street':0,
    'Sargent Terrace':0,
    'School Street':0,
    'Seafoam Avenue':0,
    'Seal Harbor Road':0,
    'Seaview Avenue':0,
    'Sewall Avenue':0,
    'Seymour Street':0,
    'Sheryl Lane':0,
    'Shirley Street':0,
    'Short Street':0,
    'Siren Street':0,
    'Somerset Avenue':0,
    'Somerset Terrace':0,
    'South Avenue':0,
    'Sturgis Street':0,
    'Summit Avenue':0,
    'Summit Avenue Path':0,
    'Sunnyside Avenue':0,
    'Sunset Road':0,
    'Surfside Avenue':0,
    'Syren Street':0,
    'Tafts Avenue':0,
    'Taylor Street':0,
    'Temple Avenue':0,
    'Terrace Avenue':0,
    'Tewksbury Street':0,
    'The Strand':0, # add these
    'Strand Way':0, #<-
    'Thornton Park':0,
    'Thornton Street':0,
    'Tileston Road':0,
    'Townsend Street':0,
    'Trident Avenue':0,
    'Triton Avenue':0,
    'Triton Street':0,
    'Underhill Street':0,
    'Undine Avenue':0,
    'Upland Road':0,
    'Veterans Road':0,
    'Villa Avenue':0,
    'Vine Avenue':0,
    'Wadsworth Avenue':0,
    'Waldemar Avenue':0,
    'Walden Place':0,
    'Walden Street':0,
    'Washington Avenue':0,
    'Washington Terrace':0,
    'Waveway Avenue':0,
    'Wheelock Street':0,
    'Whittier Street':0,
    'Williams Street':0,
    'Willis Avenue':0,
    'Willow Avenue':0,
    'Willow Terrace':0,
    'Wilshire Street':0,
    'Winthrop Shore Drive':0,
    'Winthrop Street':0,
    'Woodside Avenue':0,
    'Woodside Park':0,
    'Wyman Street':0
}