
ABV = {
    ' rd ' : 'road' ,
    ' rd. ' : 'road',

    ' st ' : 'street',
    ' st. ' : 'street',

    ' ave ' : 'avenue',
    ' ave. ' : 'avenue',
    
}
AS = {
    'adams street' :0,
    'albert avenue':0,
    'almont street':0,
    'amelia avenue':0,
    'anderson street':0,
    'andrew street':0,
    'argyle street':0,
    'atkinson circle':0,
    'atlantic street':0,
    'banks street':0,
    'bartlett parkway':0,
    'bartlett road':0,
    'bates avenue':0,
    'bay view avenue':0,
    'bayou street':0,
    'beach road':0,
    'beacon street':0,
    'beal street':0,
    'belcher street':0,
    'belle isle terrace':0,
    'bellevue avenue':0,
    'bellevue terrace':0,
    'billows street':0,
    'birch road':0,
    'bowdoin street':0,
    'brewster avenue':0,
    'brookfield road':0,
    'buchanan street':0,
    'buckthorn terrace':0,
    'burrill terrace':0,
    'central street':0,
    'centre street':0,
    'chamberlain avenue':0,
    'charles street':0,
    'chester avenue':0,
    'circuit road':0,
    'cliff avenue':0,
    'cora street':0,
    'coral avenue':0,
    'corinha beach road':0,
    'cottage avenue':0,
    'cottage park road':0,
    'court road':0,
    'crescent street':0,
    'crest avenue':0,
    'cross street':0,
    'crystal cove avenue':0,
    'cutler street':0,
    'deane avenue':0,
    'deepwater street' :0,
    'dix street' :0,
    'dolphin avenue' :0,
    'douglas street':0,
    'edgar terrace':0,
    'edgehill road':0,
    'edward street':0,
    'egleton park':0,
    'eleanor court':0,
    'elliot street':0,
    'elmer avenue':0,
    'elmwood avenue':0,
    'elmwood court':0,
    'emerson road':0,
    'enfield road':0,
    'fairview street':0,
    'faunbar avenue':0,
    'floyd street':0,
    'foam street':0,
    'forrest street':0,
    'frances street':0,
    'franklin street':0,
    'fremont street':0,
    'george street':0,
    'girdlestone road':0,
    'golden drive':0,
    'governors drive':0,
    'grand view avenue':0,
    'green hill path':0,
    'grovers avenue':0,
    'hadasa way':0,
    'hagman road':0,
    'hale avenue':0,
    'harbor view avenue':0,
    'harvard street':0,
    'hawthorn avenue':0, # same v
    'hawthorne avenue':0, # as this
    'hermon street':0,
    'highland avenue':0,
    'hillside avenue':0,
    'hutchinson street':0,
    'ingleside avenue':0,
    'irwin street':0,
    'james avenue':0,
    'jefferson street':0,
    'jerald street':0,
    'johnson avenue':0,
    'johnson terrace':0,
    'kay street':0,
    'kennedy drive':0,
    'kennedy road':0,
    'lewis avenue':0,
    'lewis terrace':0,
    'lincoln street':0,
    'lincoln terrace':0,
    'linden street':0,
    'locust street':0,
    'locust way':0,
    'lorean terrace':0,
    'loring road':0,
    'lowell road':0,
    'madison avenue':0,
    'main street':0,
    'maple road':0,
    'marshall street':0,
    'maryland avenue':0,
    'medcalf square':0,
    'mermaid avenue':0,
    'michaels mall':0,
    'moore street':0,
    'morton street':0,
    'mugford street':0,
    'myrtle avenue':0,
    'nahant avenue':0,
    'neptune avenue':0,
    'nevada street':0,
    'north avenue':0,
    'ocean avenue':0,
    'oceanview street':0,
    'oceanview way':0,
    'orlando avenue':0,
    'otis street':0,
    'overlook drive':0,
    'paine street':0,
    'palmyra street':0,
    'park avenue':0,
    'pauline street':0,
    'payson street':0,
    'pearl avenue':0,
    'pebble avenue':0,
    'perkins street':0,
    'pico avenue':0,
    'pleasant court':0,
    'pleasant park road':0,
    'pleasant street':0,
    'plummer avenue':0,
    'pond street':0,
    'pratt street':0,
    'prescott street':0,
    'prospect avenue':0,
    'putnam place':0,
    'putnam street':0,
    'quincy avenue':0,
    'quincy path':0,
    'read street':0,
    'revere street':0,
    'rice wharf':0,
    'river road':0,
    'russell street':0,
    'sagamore avenue':0,
    'sargent street':0,
    'sargent terrace':0,
    'school street':0,
    'seafoam avenue':0,
    'seal harbor road':0,
    'seaview avenue':0,
    'sewall avenue':0,
    'seymour street':0,
    'sheryl lane':0,
    'shirley street':0,
    'short street':0,
    'siren street':0,
    'somerset avenue':0,
    'somerset terrace':0,
    'south avenue':0,
    'sturgis street':0,
    'summit avenue':0,
    'summit avenue path':0,
    'sunnyside avenue':0,
    'sunset road':0,
    'surfside avenue':0,
    'syren street':0,
    'tafts avenue':0,
    'taylor street':0,
    'temple avenue':0,
    'terrace avenue':0,
    'tewksbury street':0,
    'the strand':0, # add these
    'strand way':0, #<-
    'thornton park':0,
    'thornton street':0,
    'tileston road':0,
    'townsend street':0,
    'trident avenue':0,
    'triton avenue':0,
    'underhill street':0,
    'undine avenue':0,
    'upland road':0,
    'veterans road':0,
    'villa avenue':0,
    'vine avenue':0,
    'wadsworth avenue':0,
    'waldemar avenue':0,
    'walden place':0,
    'walden street':0,
    'washington avenue':0,
    'washington terrace':0,
    'waveway avenue':0,
    'wheelock street':0,
    'whittier street':0,
    'williams street':0,
    'willis avenue':0,
    'willow avenue':0,
    'willow terrace':0,
    'wilshire street':0,
    'winthrop shore drive':0,
    'shore drive':0,
    'winthrop parkway':0,
    'winthrop street':0,
    'woodside avenue':0,
    'woodside park':0,
    'wyman street':0
}